// Code generated by goyacc -p expr -o pkg/logql/expr.y.go pkg/logql/expr.y. DO NOT EDIT.

package logql

import __yyfmt__ "fmt"


import (
	"github.com/grafana/loki/pkg/logql/log"
	"github.com/prometheus/prometheus/pkg/labels"
	"time"
)

type exprSymType struct {
	yys                   int
	Expr                  Expr
	Filter                labels.MatchType
	Grouping              *grouping
	Labels                []string
	LogExpr               LogSelectorExpr
	LogRangeExpr          *logRange
	Matcher               *labels.Matcher
	Matchers              []*labels.Matcher
	RangeAggregationExpr  SampleExpr
	RangeOp               string
	ConvOp                string
	Selector              []*labels.Matcher
	VectorAggregationExpr SampleExpr
	MetricExpr            SampleExpr
	VectorOp              string
	FilterOp              string
	BinOpExpr             SampleExpr
	LabelReplaceExpr      SampleExpr
	binOp                 string
	bytes                 uint64
	str                   string
	duration              time.Duration
	LiteralExpr           *literalExpr
	BinOpModifier         BinOpOptions
	LabelParser           *labelParserExpr
	LineFilters           *lineFilterExpr
	FunctionFilter        *functionLineFilterExpr
	PipelineExpr          MultiStageExpr
	PipelineStage         StageExpr
	BytesFilter           log.LabelFilterer
	NumberFilter          log.LabelFilterer
	DurationFilter        log.LabelFilterer
	LabelFilter           log.LabelFilterer
	UnitFilter            log.LabelFilterer
	LineFormatExpr        *lineFmtExpr
	LabelFormatExpr       *labelFmtExpr
	LabelFormat           log.LabelFmt
	LabelsFormat          []log.LabelFmt
	JSONExpressionParser  *jsonExpressionParser
	JSONExpression        log.JSONExpression
	JSONExpressionList    []log.JSONExpression
	UnwrapExpr            *unwrapExpr
}

const BYTES = 57346
const IDENTIFIER = 57347
const STRING = 57348
const NUMBER = 57349
const DURATION = 57350
const RANGE = 57351
const MATCHERS = 57352
const LABELS = 57353
const EQ = 57354
const RE = 57355
const NRE = 57356
const OPEN_BRACE = 57357
const CLOSE_BRACE = 57358
const OPEN_BRACKET = 57359
const CLOSE_BRACKET = 57360
const COMMA = 57361
const DOT = 57362
const PIPE_MATCH = 57363
const PIPE_EXACT = 57364
const OPEN_PARENTHESIS = 57365
const CLOSE_PARENTHESIS = 57366
const BY = 57367
const WITHOUT = 57368
const COUNT_OVER_TIME = 57369
const RATE = 57370
const SUM = 57371
const AVG = 57372
const MAX = 57373
const MIN = 57374
const COUNT = 57375
const STDDEV = 57376
const STDVAR = 57377
const BOTTOMK = 57378
const TOPK = 57379
const BYTES_OVER_TIME = 57380
const BYTES_RATE = 57381
const BOOL = 57382
const JSON = 57383
const REGEXP = 57384
const LOGFMT = 57385
const PIPE = 57386
const LINE_FMT = 57387
const LABEL_FMT = 57388
const UNWRAP = 57389
const AVG_OVER_TIME = 57390
const SUM_OVER_TIME = 57391
const MIN_OVER_TIME = 57392
const MAX_OVER_TIME = 57393
const STDVAR_OVER_TIME = 57394
const STDDEV_OVER_TIME = 57395
const QUANTILE_OVER_TIME = 57396
const BYTES_CONV = 57397
const DURATION_CONV = 57398
const DURATION_SECONDS_CONV = 57399
const ABSENT_OVER_TIME = 57400
const LABEL_REPLACE = 57401
const IP = 57402
const OR = 57403
const AND = 57404
const UNLESS = 57405
const CMP_EQ = 57406
const NEQ = 57407
const LT = 57408
const LTE = 57409
const GT = 57410
const GTE = 57411
const ADD = 57412
const SUB = 57413
const MUL = 57414
const DIV = 57415
const MOD = 57416
const POW = 57417

var exprToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"BYTES",
	"IDENTIFIER",
	"STRING",
	"NUMBER",
	"DURATION",
	"RANGE",
	"MATCHERS",
	"LABELS",
	"EQ",
	"RE",
	"NRE",
	"OPEN_BRACE",
	"CLOSE_BRACE",
	"OPEN_BRACKET",
	"CLOSE_BRACKET",
	"COMMA",
	"DOT",
	"PIPE_MATCH",
	"PIPE_EXACT",
	"OPEN_PARENTHESIS",
	"CLOSE_PARENTHESIS",
	"BY",
	"WITHOUT",
	"COUNT_OVER_TIME",
	"RATE",
	"SUM",
	"AVG",
	"MAX",
	"MIN",
	"COUNT",
	"STDDEV",
	"STDVAR",
	"BOTTOMK",
	"TOPK",
	"BYTES_OVER_TIME",
	"BYTES_RATE",
	"BOOL",
	"JSON",
	"REGEXP",
	"LOGFMT",
	"PIPE",
	"LINE_FMT",
	"LABEL_FMT",
	"UNWRAP",
	"AVG_OVER_TIME",
	"SUM_OVER_TIME",
	"MIN_OVER_TIME",
	"MAX_OVER_TIME",
	"STDVAR_OVER_TIME",
	"STDDEV_OVER_TIME",
	"QUANTILE_OVER_TIME",
	"BYTES_CONV",
	"DURATION_CONV",
	"DURATION_SECONDS_CONV",
	"ABSENT_OVER_TIME",
	"LABEL_REPLACE",
	"IP",
	"OR",
	"AND",
	"UNLESS",
	"CMP_EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"ADD",
	"SUB",
	"MUL",
	"DIV",
	"MOD",
	"POW",
}

var exprStatenames = [...]string{}

const exprEofCode = 1
const exprErrCode = 2
const exprInitialStackSize = 16


var exprExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const exprPrivate = 57344

const exprLast = 464

var exprAct = [...]int{
	74, 188, 4, 168, 162, 56, 197, 108, 157, 65,
	55, 67, 2, 5, 131, 45, 46, 47, 48, 48,
	70, 40, 41, 42, 49, 50, 53, 54, 51, 52,
	43, 44, 45, 46, 47, 48, 41, 42, 49, 50,
	53, 54, 51, 52, 43, 44, 45, 46, 47, 48,
	43, 44, 45, 46, 47, 48, 119, 242, 239, 283,
	81, 96, 184, 73, 118, 75, 76, 297, 102, 170,
	129, 130, 75, 76, 293, 114, 135, 127, 129, 130,
	64, 60, 140, 288, 263, 276, 133, 63, 98, 159,
	295, 262, 141, 111, 142, 143, 144, 145, 146, 147,
	148, 149, 150, 151, 152, 153, 154, 155, 49, 50,
	53, 54, 51, 52, 43, 44, 45, 46, 47, 48,
	165, 176, 171, 174, 175, 172, 173, 120, 64, 240,
	128, 99, 158, 179, 64, 63, 61, 199, 251, 97,
	195, 63, 61, 253, 189, 251, 200, 240, 191, 192,
	252, 261, 64, 249, 193, 266, 201, 238, 190, 63,
	61, 187, 274, 114, 190, 199, 64, 203, 204, 205,
	286, 266, 273, 63, 61, 187, 243, 159, 267, 62,
	64, 111, 190, 122, 198, 62, 234, 63, 61, 236,
	239, 241, 239, 244, 247, 96, 190, 248, 237, 102,
	133, 235, 245, 62, 114, 238, 239, 64, 114, 121,
	190, 255, 184, 257, 63, 61, 292, 62, 159, 160,
	158, 281, 111, 208, 114, 132, 111, 184, 269, 270,
	271, 62, 114, 12, 246, 178, 12, 59, 159, 264,
	239, 134, 111, 96, 134, 177, 139, 275, 265, 185,
	111, 96, 138, 277, 137, 79, 72, 279, 62, 15,
	160, 158, 250, 209, 280, 206, 202, 12, 105, 107,
	106, 126, 112, 113, 282, 6, 194, 287, 124, 19,
	20, 31, 32, 34, 35, 33, 36, 37, 38, 39,
	21, 22, 123, 186, 210, 125, 207, 291, 285, 284,
	23, 24, 25, 26, 27, 28, 29, 272, 196, 230,
	30, 18, 231, 229, 78, 215, 12, 181, 216, 214,
	259, 260, 16, 17, 6, 77, 114, 290, 19, 20,
	31, 32, 34, 35, 33, 36, 37, 38, 39, 21,
	22, 3, 296, 212, 111, 180, 213, 211, 66, 23,
	24, 25, 26, 27, 28, 29, 278, 136, 294, 30,
	18, 289, 105, 107, 106, 12, 112, 113, 242, 256,
	254, 16, 17, 6, 233, 232, 183, 19, 20, 31,
	32, 34, 35, 33, 36, 37, 38, 39, 21, 22,
	80, 227, 182, 224, 228, 226, 225, 223, 23, 24,
	25, 26, 27, 28, 29, 181, 180, 221, 30, 18,
	222, 220, 218, 166, 258, 219, 217, 169, 109, 164,
	16, 17, 156, 117, 69, 163, 71, 71, 169, 161,
	101, 167, 82, 83, 84, 85, 86, 87, 88, 89,
	90, 91, 92, 93, 94, 95, 104, 103, 57, 58,
	115, 110, 116, 100, 11, 10, 9, 14, 8, 268,
	13, 7, 68, 1,
}

var exprPact = [...]int{
	252, -1000, -40, -1000, -1000, 193, 252, -1000, -1000, -1000,
	-1000, -1000, 422, 233, 40, -1000, 318, 307, 232, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
	20, 20, 20, 20, 20, 193, -1000, 66, -1000, 227,
	417, -4, -4, -1000, -1000, 185, 159, -40, 276, 255,
	-1000, 65, 218, 350, 231, 229, 223, -1000, -1000, 252,
	252, -1000, 252, 252, 252, 252, 252, 252, 252, 252,
	252, 252, 252, 252, 252, 252, -1000, 416, -1000, -1000,
	-1000, -1000, 158, -1000, -1000, 420, -1000, 413, -1000, -1000,
	-1000, 203, 407, 423, 57, -1000, -1000, -1000, 222, -1000,
	212, -1000, -1000, -1000, -1000, 421, -1000, 400, 399, 386,
	370, 225, 274, 166, 221, 130, 257, 301, 160, 132,
	247, -26, 44, 44, -57, -57, -56, -56, -56, -56,
	-20, -20, -20, -20, -20, -20, -1000, 158, 203, 203,
	203, 246, -1000, 284, -1000, 199, -1000, 244, -1000, 282,
	339, 311, 408, 403, 389, 387, 305, 369, 368, -1000,
	-1000, -1000, -1000, -1000, -1000, 47, 221, 114, 196, 120,
	321, 152, 210, 47, 252, 129, 243, 126, -1000, -1000,
	119, -1000, 364, 219, 158, 70, 420, 363, -1000, 412,
	315, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 127, 67, -1000, 60, 14, 114, -1000, 203,
	-1000, 162, 173, 298, 148, 138, -1000, -1000, 61, -1000,
	252, 351, -1000, -1000, 238, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 47, 14, 158, -1000, -1000, 198, -1000,
	-1000, -1000, 15, 290, 289, 146, 47, 59, -1000, 355,
	-1000, 322, 14, 10, -1000, -1000, 288, -1000, -1000, 197,
	50, -1000, 352, -1000, 71, 336, 43, -1000,
}

var exprPgo = [...]int{
	0, 463, 11, 81, 0, 6, 341, 2, 14, 7,
	462, 461, 460, 459, 13, 458, 457, 64, 456, 455,
	454, 390, 453, 10, 5, 452, 451, 450, 8, 449,
	448, 447, 446, 3, 431, 430, 4, 429, 1, 418,
}

var exprR1 = [...]int{
	0, 1, 2, 2, 7, 7, 7, 7, 7, 7,
	6, 6, 6, 8, 8, 8, 8, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 8, 38, 38, 38,
	13, 13, 13, 11, 11, 11, 11, 15, 15, 15,
	15, 15, 15, 20, 3, 3, 3, 3, 14, 14,
	14, 10, 10, 9, 9, 9, 9, 23, 23, 24,
	24, 24, 24, 24, 24, 24, 17, 29, 29, 30,
	30, 22, 22, 22, 35, 31, 33, 33, 34, 34,
	34, 32, 28, 28, 28, 28, 28, 28, 28, 28,
	36, 37, 37, 39, 39, 27, 27, 27, 27, 27,
	27, 27, 25, 25, 25, 25, 25, 25, 25, 26,
	26, 26, 26, 26, 26, 26, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 21, 21, 19, 19, 19, 16, 16, 16, 16,
	16, 16, 16, 16, 16, 12, 12, 12, 12, 12,
	12, 12, 12, 12, 12, 12, 12, 5, 5, 4,
	4, 4, 4,
}

var exprR2 = [...]int{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 3,
	1, 2, 3, 2, 4, 3, 5, 3, 5, 3,
	5, 4, 6, 3, 4, 3, 2, 3, 6, 3,
	1, 1, 1, 4, 6, 5, 7, 4, 5, 5,
	6, 7, 7, 12, 1, 1, 1, 1, 3, 3,
	3, 1, 3, 3, 3, 3, 3, 1, 2, 1,
	1, 2, 2, 2, 2, 2, 1, 5, 5, 2,
	3, 1, 1, 2, 2, 2, 3, 3, 1, 3,
	3, 2, 1, 1, 1, 3, 2, 3, 3, 3,
	3, 1, 3, 1, 1, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 0, 1, 1, 2, 2, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 3, 4,
	4, 3, 3,
}

var exprChk = [...]int{
	-1000, -1, -2, -6, -7, -14, 23, -11, -15, -18,
	-19, -20, 15, -12, -16, 7, 70, 71, 59, 27,
	28, 38, 39, 48, 49, 50, 51, 52, 53, 54,
	58, 29, 30, 33, 31, 32, 34, 35, 36, 37,
	61, 62, 63, 70, 71, 72, 73, 74, 75, 64,
	65, 68, 69, 66, 67, -23, -24, -30, -29, 44,
	-3, 22, 65, 21, 14, -7, -6, -2, -10, 2,
	-9, 5, 23, 23, -4, 25, 26, 7, 7, 23,
	-21, 40, -21, -21, -21, -21, -21, -21, -21, -21,
	-21, -21, -21, -21, -21, -21, -24, -3, 22, 65,
	-22, -35, -28, -31, -32, 41, 43, 42, -9, -39,
	-26, 23, 45, 46, 5, -27, -25, 6, -17, 60,
	-17, 24, 24, 16, 2, 19, 16, 12, 65, 13,
	14, -8, 7, -14, 23, -7, 7, 23, 23, 23,
	-7, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -2, 6, -28, 62, 19,
	61, -37, -36, 5, 6, -28, 6, -34, -33, 5,
	12, 65, 68, 69, 66, 67, 64, 23, 23, -9,
	6, 6, 6, 6, 2, 24, 19, 9, -38, -23,
	44, -14, -8, 24, 19, -7, 7, -5, 24, 5,
	-5, 24, 19, -28, -28, -28, 19, 12, 24, 19,
	12, 8, 4, 7, 8, 4, 7, 8, 4, 7,
	8, 4, 7, 8, 4, 7, 8, 4, 7, 8,
	4, 7, 6, 6, -4, -8, -38, -23, 9, 44,
	9, -38, 47, 24, -38, -23, 24, -4, -7, 24,
	19, 19, 24, 24, 6, -36, 6, -33, 2, 5,
	6, 24, 24, 24, -38, -28, 9, 5, -13, 55,
	56, 57, 9, 24, 24, -38, 24, -7, 5, 19,
	-4, 23, -38, 44, 9, 9, 24, -4, 24, 6,
	5, 9, 19, 24, 6, 19, 6, 24,
}

var exprDef = [...]int{
	0, -2, 1, 2, 3, 10, 0, 4, 5, 6,
	7, 8, 0, 0, 0, 133, 0, 0, 0, 145,
	146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
	156, 136, 137, 138, 139, 140, 141, 142, 143, 144,
	131, 131, 131, 131, 131, 131, 131, 131, 131, 131,
	131, 131, 131, 131, 131, 11, 57, 59, 60, 0,
	0, 45, 47, 44, 46, 3, 2, 0, 0, 0,
	51, 0, 0, 0, 0, 0, 0, 134, 135, 0,
	0, 132, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 58, 0, 45, 47,
	61, 62, 63, 64, 65, 71, 72, 0, 82, 83,
	84, 0, 0, 0, 0, 93, 94, 69, 0, 66,
	0, 9, 12, 48, 49, 0, 50, 0, 0, 0,
	0, 0, 0, 0, 0, 3, 133, 0, 0, 0,
	3, 116, 117, 118, 119, 120, 121, 122, 123, 124,
	125, 126, 127, 128, 129, 130, 70, 86, 0, 0,
	0, 74, 91, 0, 73, 0, 75, 81, 78, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 52,
	53, 54, 55, 56, 26, 33, 0, 13, 0, 0,
	0, 0, 0, 37, 0, 3, 133, 0, 161, 157,
	0, 162, 0, 87, 88, 89, 0, 0, 85, 0,
	0, 100, 107, 114, 99, 106, 113, 95, 102, 109,
	96, 103, 110, 97, 104, 111, 98, 105, 112, 101,
	108, 115, 0, 0, 35, 0, 15, 23, 17, 0,
	19, 0, 0, 0, 0, 0, 25, 39, 3, 38,
	0, 0, 159, 160, 0, 92, 90, 79, 80, 76,
	77, 67, 68, 34, 24, 29, 21, 27, 0, 30,
	31, 32, 14, 0, 0, 0, 40, 3, 158, 0,
	36, 0, 16, 0, 18, 20, 0, 41, 42, 0,
	0, 22, 0, 28, 0, 0, 0, 43,
}

var exprTok1 = [...]int{
	1,
}

var exprTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75,
}

var exprTok3 = [...]int{
	0,
}

var exprErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}


/*	parser for yacc output	*/

var (
	exprDebug        = 0
	exprErrorVerbose = false
)

type exprLexer interface {
	Lex(lval *exprSymType) int
	Error(s string)
}

type exprParser interface {
	Parse(exprLexer) int
	Lookahead() int
}

type exprParserImpl struct {
	lval  exprSymType
	stack [exprInitialStackSize]exprSymType
	char  int
}

func (p *exprParserImpl) Lookahead() int {
	return p.char
}

func exprNewParser() exprParser {
	return &exprParserImpl{}
}

const exprFlag = -1000

func exprTokname(c int) string {
	if c >= 1 && c-1 < len(exprToknames) {
		if exprToknames[c-1] != "" {
			return exprToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func exprStatname(s int) string {
	if s >= 0 && s < len(exprStatenames) {
		if exprStatenames[s] != "" {
			return exprStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func exprErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !exprErrorVerbose {
		return "syntax error"
	}

	for _, e := range exprErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + exprTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := exprPact[state]
	for tok := TOKSTART; tok-1 < len(exprToknames); tok++ {
		if n := base + tok; n >= 0 && n < exprLast && exprChk[exprAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if exprDef[state] == -2 {
		i := 0
		for exprExca[i] != -1 || exprExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; exprExca[i] >= 0; i += 2 {
			tok := exprExca[i]
			if tok < TOKSTART || exprExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if exprExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += exprTokname(tok)
	}
	return res
}

func exprlex1(lex exprLexer, lval *exprSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = exprTok1[0]
		goto out
	}
	if char < len(exprTok1) {
		token = exprTok1[char]
		goto out
	}
	if char >= exprPrivate {
		if char < exprPrivate+len(exprTok2) {
			token = exprTok2[char-exprPrivate]
			goto out
		}
	}
	for i := 0; i < len(exprTok3); i += 2 {
		token = exprTok3[i+0]
		if token == char {
			token = exprTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = exprTok2[1] /* unknown char */
	}
	if exprDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", exprTokname(token), uint(char))
	}
	return char, token
}

func exprParse(exprlex exprLexer) int {
	return exprNewParser().Parse(exprlex)
}

func (exprrcvr *exprParserImpl) Parse(exprlex exprLexer) int {
	var exprn int
	var exprVAL exprSymType
	var exprDollar []exprSymType
	_ = exprDollar // silence set and not used
	exprS := exprrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	exprstate := 0
	exprrcvr.char = -1
	exprtoken := -1 // exprrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		exprstate = -1
		exprrcvr.char = -1
		exprtoken = -1
	}()
	exprp := -1
	goto exprstack

ret0:
	return 0

ret1:
	return 1

exprstack:
	/* put a state and value onto the stack */
	if exprDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", exprTokname(exprtoken), exprStatname(exprstate))
	}

	exprp++
	if exprp >= len(exprS) {
		nyys := make([]exprSymType, len(exprS)*2)
		copy(nyys, exprS)
		exprS = nyys
	}
	exprS[exprp] = exprVAL
	exprS[exprp].yys = exprstate

exprnewstate:
	exprn = exprPact[exprstate]
	if exprn <= exprFlag {
		goto exprdefault /* simple state */
	}
	if exprrcvr.char < 0 {
		exprrcvr.char, exprtoken = exprlex1(exprlex, &exprrcvr.lval)
	}
	exprn += exprtoken
	if exprn < 0 || exprn >= exprLast {
		goto exprdefault
	}
	exprn = exprAct[exprn]
	if exprChk[exprn] == exprtoken { /* valid shift */
		exprrcvr.char = -1
		exprtoken = -1
		exprVAL = exprrcvr.lval
		exprstate = exprn
		if Errflag > 0 {
			Errflag--
		}
		goto exprstack
	}

exprdefault:
	/* default state action */
	exprn = exprDef[exprstate]
	if exprn == -2 {
		if exprrcvr.char < 0 {
			exprrcvr.char, exprtoken = exprlex1(exprlex, &exprrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if exprExca[xi+0] == -1 && exprExca[xi+1] == exprstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			exprn = exprExca[xi+0]
			if exprn < 0 || exprn == exprtoken {
				break
			}
		}
		exprn = exprExca[xi+1]
		if exprn < 0 {
			goto ret0
		}
	}
	if exprn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			exprlex.Error(exprErrorMessage(exprstate, exprtoken))
			Nerrs++
			if exprDebug >= 1 {
				__yyfmt__.Printf("%s", exprStatname(exprstate))
				__yyfmt__.Printf(" saw %s\n", exprTokname(exprtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for exprp >= 0 {
				exprn = exprPact[exprS[exprp].yys] + exprErrCode
				if exprn >= 0 && exprn < exprLast {
					exprstate = exprAct[exprn] /* simulate a shift of "error" */
					if exprChk[exprstate] == exprErrCode {
						goto exprstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if exprDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", exprS[exprp].yys)
				}
				exprp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if exprDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", exprTokname(exprtoken))
			}
			if exprtoken == exprEofCode {
				goto ret1
			}
			exprrcvr.char = -1
			exprtoken = -1
			goto exprnewstate /* try again in the same state */
		}
	}

	/* reduction by production exprn */
	if exprDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", exprn, exprStatname(exprstate))
	}

	exprnt := exprn
	exprpt := exprp
	_ = exprpt // guard against "declared and not used"

	exprp -= exprR2[exprn]
	// exprp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if exprp+1 >= len(exprS) {
		nyys := make([]exprSymType, len(exprS)*2)
		copy(nyys, exprS)
		exprS = nyys
	}
	exprVAL = exprS[exprp+1]

	/* consult goto table to find next state */
	exprn = exprR1[exprn]
	exprg := exprPgo[exprn]
	exprj := exprg + exprS[exprp].yys + 1

	if exprj >= exprLast {
		exprstate = exprAct[exprg]
	} else {
		exprstate = exprAct[exprj]
		if exprChk[exprstate] != -exprn {
			exprstate = exprAct[exprg]
		}
	}
	// dummy call; replaced with literal code
	switch exprnt {

	case 1:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprlex.(*parser).expr = exprDollar[1].Expr
		}
	case 2:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Expr = exprDollar[1].LogExpr
		}
	case 3:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Expr = exprDollar[1].MetricExpr
		}
	case 4:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricExpr = exprDollar[1].RangeAggregationExpr
		}
	case 5:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricExpr = exprDollar[1].VectorAggregationExpr
		}
	case 6:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricExpr = exprDollar[1].BinOpExpr
		}
	case 7:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricExpr = exprDollar[1].LiteralExpr
		}
	case 8:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricExpr = exprDollar[1].LabelReplaceExpr
		}
	case 9:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.MetricExpr = exprDollar[2].MetricExpr
		}
	case 10:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LogExpr = newMatcherExpr(exprDollar[1].Selector)
		}
	case 11:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogExpr = newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].PipelineExpr)
		}
	case 12:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogExpr = exprDollar[2].LogExpr
		}
	case 13:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].duration, nil)
		}
	case 14:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[2].Selector), exprDollar[4].duration, nil)
		}
	case 15:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].duration, exprDollar[3].UnwrapExpr)
		}
	case 16:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[2].Selector), exprDollar[4].duration, exprDollar[5].UnwrapExpr)
		}
	case 17:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[1].Selector), exprDollar[3].duration, exprDollar[2].UnwrapExpr)
		}
	case 18:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newMatcherExpr(exprDollar[2].Selector), exprDollar[5].duration, exprDollar[3].UnwrapExpr)
		}
	case 19:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].PipelineExpr), exprDollar[3].duration, nil)
		}
	case 20:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[2].Selector), exprDollar[3].PipelineExpr), exprDollar[5].duration, nil)
		}
	case 21:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[2].PipelineExpr), exprDollar[4].duration, exprDollar[3].UnwrapExpr)
		}
	case 22:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[2].Selector), exprDollar[3].PipelineExpr), exprDollar[6].duration, exprDollar[4].UnwrapExpr)
		}
	case 23:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[3].PipelineExpr), exprDollar[2].duration, nil)
		}
	case 24:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(exprDollar[1].Selector), exprDollar[3].PipelineExpr), exprDollar[2].duration, exprDollar[4].UnwrapExpr)
		}
	case 25:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeExpr = exprDollar[2].LogRangeExpr
		}
	case 27:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.UnwrapExpr = newUnwrapExpr(exprDollar[3].str, "")
		}
	case 28:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.UnwrapExpr = newUnwrapExpr(exprDollar[5].str, exprDollar[3].ConvOp)
		}
	case 29:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.UnwrapExpr = exprDollar[1].UnwrapExpr.addPostFilter(exprDollar[3].LabelFilter)
		}
	case 30:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ConvOp = OpConvBytes
		}
	case 31:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ConvOp = OpConvDuration
		}
	case 32:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ConvOp = OpConvDurationSeconds
		}
	case 33:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.RangeAggregationExpr = newRangeAggregationExpr(exprDollar[3].LogRangeExpr, exprDollar[1].RangeOp, nil, nil)
		}
	case 34:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.RangeAggregationExpr = newRangeAggregationExpr(exprDollar[5].LogRangeExpr, exprDollar[1].RangeOp, nil, &exprDollar[3].str)
		}
	case 35:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.RangeAggregationExpr = newRangeAggregationExpr(exprDollar[3].LogRangeExpr, exprDollar[1].RangeOp, exprDollar[5].Grouping, nil)
		}
	case 36:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.RangeAggregationExpr = newRangeAggregationExpr(exprDollar[5].LogRangeExpr, exprDollar[1].RangeOp, exprDollar[7].Grouping, &exprDollar[3].str)
		}
	case 37:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[3].MetricExpr, exprDollar[1].VectorOp, nil, nil)
		}
	case 38:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[4].MetricExpr, exprDollar[1].VectorOp, exprDollar[2].Grouping, nil)
		}
	case 39:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[3].MetricExpr, exprDollar[1].VectorOp, exprDollar[5].Grouping, nil)
		}
	case 40:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[5].MetricExpr, exprDollar[1].VectorOp, nil, &exprDollar[3].str)
		}
	case 41:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[5].MetricExpr, exprDollar[1].VectorOp, exprDollar[7].Grouping, &exprDollar[3].str)
		}
	case 42:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.VectorAggregationExpr = mustNewVectorAggregationExpr(exprDollar[6].MetricExpr, exprDollar[1].VectorOp, exprDollar[2].Grouping, &exprDollar[4].str)
		}
	case 43:
		exprDollar = exprS[exprpt-12 : exprpt+1]
		{
			exprVAL.LabelReplaceExpr = mustNewLabelReplaceExpr(exprDollar[3].MetricExpr, exprDollar[5].str, exprDollar[7].str, exprDollar[9].str, exprDollar[11].str)
		}
	case 44:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = labels.MatchRegexp
		}
	case 45:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = labels.MatchEqual
		}
	case 46:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = labels.MatchNotRegexp
		}
	case 47:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = labels.MatchNotEqual
		}
	case 48:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Selector = exprDollar[2].Matchers
		}
	case 49:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Selector = exprDollar[2].Matchers
		}
	case 50:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
		}
	case 51:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Matchers = []*labels.Matcher{exprDollar[1].Matcher}
		}
	case 52:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matchers = append(exprDollar[1].Matchers, exprDollar[3].Matcher)
		}
	case 53:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = mustNewMatcher(labels.MatchEqual, exprDollar[1].str, exprDollar[3].str)
		}
	case 54:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = mustNewMatcher(labels.MatchNotEqual, exprDollar[1].str, exprDollar[3].str)
		}
	case 55:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = mustNewMatcher(labels.MatchRegexp, exprDollar[1].str, exprDollar[3].str)
		}
	case 56:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = mustNewMatcher(labels.MatchNotRegexp, exprDollar[1].str, exprDollar[3].str)
		}
	case 57:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.PipelineExpr = MultiStageExpr{exprDollar[1].PipelineStage}
		}
	case 58:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.PipelineExpr = append(exprDollar[1].PipelineExpr, exprDollar[2].PipelineStage)
		}
	case 59:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.PipelineStage = exprDollar[1].LineFilters
		}
	case 60:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.PipelineStage = exprDollar[1].FunctionFilter
		}
	case 61:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.PipelineStage = exprDollar[2].LabelParser
		}
	case 62:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.PipelineStage = exprDollar[2].JSONExpressionParser
		}
	case 63:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.PipelineStage = &labelFilterExpr{LabelFilterer: exprDollar[2].LabelFilter}
		}
	case 64:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.PipelineStage = exprDollar[2].LineFormatExpr
		}
	case 65:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.PipelineStage = exprDollar[2].LabelFormatExpr
		}
	case 66:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.FilterOp = OpFilterIP
		}
	case 67:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.FunctionFilter = newFunctionLineFilterExpr(exprDollar[2].FilterOp, exprDollar[4].str, labels.MatchEqual)
		}
	case 68:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.FunctionFilter = newFunctionLineFilterExpr(exprDollar[2].FilterOp, exprDollar[4].str, labels.MatchNotEqual)
		}
	case 69:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LineFilters = newLineFilterExpr(nil, exprDollar[1].Filter, exprDollar[2].str)
		}
	case 70:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LineFilters = newLineFilterExpr(exprDollar[1].LineFilters, exprDollar[2].Filter, exprDollar[3].str)
		}
	case 71:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LabelParser = newLabelParserExpr(OpParserTypeJSON, "")
		}
	case 72:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LabelParser = newLabelParserExpr(OpParserTypeLogfmt, "")
		}
	case 73:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LabelParser = newLabelParserExpr(OpParserTypeRegexp, exprDollar[2].str)
		}
	case 74:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.JSONExpressionParser = newJSONExpressionParser(exprDollar[2].JSONExpressionList)
		}
	case 75:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LineFormatExpr = newLineFmtExpr(exprDollar[2].str)
		}
	case 76:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LabelFormat = log.NewRenameLabelFmt(exprDollar[1].str, exprDollar[3].str)
		}
	case 77:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LabelFormat = log.NewTemplateLabelFmt(exprDollar[1].str, exprDollar[3].str)
		}
	case 78:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LabelsFormat = []log.LabelFmt{exprDollar[1].LabelFormat}
		}
	case 79:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LabelsFormat = append(exprDollar[1].LabelsFormat, exprDollar[3].LabelFormat)
		}
	case 81:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LabelFormatExpr = newLabelFmtExpr(exprDollar[2].LabelsFormat)
		}
	case 82:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LabelFilter = log.NewStringLabelFilter(exprDollar[1].Matcher)
		}
	case 83:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LabelFilter = exprDollar[1].UnitFilter
		}
	case 84:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LabelFilter = exprDollar[1].NumberFilter
		}
	case 85:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LabelFilter = exprDollar[2].LabelFilter
		}
	case 86:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LabelFilter = log.NewAndLabelFilter(exprDollar[1].LabelFilter, exprDollar[2].LabelFilter)
		}
	case 87:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LabelFilter = log.NewAndLabelFilter(exprDollar[1].LabelFilter, exprDollar[3].LabelFilter)
		}
	case 88:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LabelFilter = log.NewAndLabelFilter(exprDollar[1].LabelFilter, exprDollar[3].LabelFilter)
		}
	case 89:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LabelFilter = log.NewOrLabelFilter(exprDollar[1].LabelFilter, exprDollar[3].LabelFilter)
		}
	case 90:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.JSONExpression = log.NewJSONExpr(exprDollar[1].str, exprDollar[3].str)
		}
	case 91:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.JSONExpressionList = []log.JSONExpression{exprDollar[1].JSONExpression}
		}
	case 92:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.JSONExpressionList = append(exprDollar[1].JSONExpressionList, exprDollar[3].JSONExpression)
		}
	case 93:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.UnitFilter = exprDollar[1].DurationFilter
		}
	case 94:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.UnitFilter = exprDollar[1].BytesFilter
		}
	case 95:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterGreaterThan, exprDollar[1].str, exprDollar[3].duration)
		}
	case 96:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterGreaterThanOrEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 97:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterLesserThan, exprDollar[1].str, exprDollar[3].duration)
		}
	case 98:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterLesserThanOrEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 99:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterNotEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 100:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 101:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.DurationFilter = log.NewDurationLabelFilter(log.LabelFilterEqual, exprDollar[1].str, exprDollar[3].duration)
		}
	case 102:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterGreaterThan, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 103:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterGreaterThanOrEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 104:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterLesserThan, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 105:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterLesserThanOrEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 106:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterNotEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 107:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 108:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.BytesFilter = log.NewBytesLabelFilter(log.LabelFilterEqual, exprDollar[1].str, exprDollar[3].bytes)
		}
	case 109:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterGreaterThan, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 110:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterGreaterThanOrEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 111:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterLesserThan, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 112:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterLesserThanOrEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 113:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterNotEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 114:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 115:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.NumberFilter = log.NewNumericLabelFilter(log.LabelFilterEqual, exprDollar[1].str, mustNewFloat(exprDollar[3].str))
		}
	case 116:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("or", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 117:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("and", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 118:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("unless", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 119:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("+", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 120:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("-", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 121:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("*", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 122:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("/", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 123:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("%", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 124:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("^", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 125:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("==", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 126:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("!=", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 127:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr(">", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 128:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr(">=", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 129:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("<", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 130:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinOpExpr = mustNewBinOpExpr("<=", exprDollar[3].BinOpModifier, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 131:
		exprDollar = exprS[exprpt-0 : exprpt+1]
		{
			exprVAL.BinOpModifier = BinOpOptions{}
		}
	case 132:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.BinOpModifier = BinOpOptions{ReturnBool: true}
		}
	case 133:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LiteralExpr = mustNewLiteralExpr(exprDollar[1].str, false)
		}
	case 134:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LiteralExpr = mustNewLiteralExpr(exprDollar[2].str, false)
		}
	case 135:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LiteralExpr = mustNewLiteralExpr(exprDollar[2].str, true)
		}
	case 136:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeSum
		}
	case 137:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeAvg
		}
	case 138:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeCount
		}
	case 139:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeMax
		}
	case 140:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeMin
		}
	case 141:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeStddev
		}
	case 142:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeStdvar
		}
	case 143:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeBottomK
		}
	case 144:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.VectorOp = OpTypeTopK
		}
	case 145:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeCount
		}
	case 146:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeRate
		}
	case 147:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeBytes
		}
	case 148:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeBytesRate
		}
	case 149:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeAvg
		}
	case 150:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeSum
		}
	case 151:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeMin
		}
	case 152:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeMax
		}
	case 153:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeStdvar
		}
	case 154:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeStddev
		}
	case 155:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeQuantile
		}
	case 156:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.RangeOp = OpRangeTypeAbsent
		}
	case 157:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Labels = []string{exprDollar[1].str}
		}
	case 158:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Labels = append(exprDollar[1].Labels, exprDollar[3].str)
		}
	case 159:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: false, groups: exprDollar[3].Labels}
		}
	case 160:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: true, groups: exprDollar[3].Labels}
		}
	case 161:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: false, groups: nil}
		}
	case 162:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: true, groups: nil}
		}
	}
	goto exprstack /* stack new state and value */
}
