version: '3.7'

services:
  grafana:
    image: grafana/grafana:master
    volumes:
    - ./:/etc/grafana/provisioning/datasources/
    ports:
      - "3000:3000"
    environment:
      GF_EXPLORE_ENABLED: "true"

  loki:
    image: grafana/loki:master-1269c92
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
