{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "loki.fullname" . }}
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      name: loki
      name: {{ template "loki.fullname" . }}
      app: {{ template "loki.name" . }}
      release: {{ .Release.Name }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            name: loki
            app: {{ template "promtail.name" . }}
            release: {{ .Release.Name }}
    - ports:
      - port: {{ .Values.service.port }}
{{- end -}}
