kind: pipeline
name: check
steps:
- commands:
  - make BUILD_IN_CONTAINER=false test
  depends_on:
  - clone
  image: grafana/loki-build-image:0.7.4
  name: test
- commands:
  - make BUILD_IN_CONTAINER=false lint
  depends_on:
  - clone
  image: grafana/loki-build-image:0.7.4
  name: lint
- commands:
  - make BUILD_IN_CONTAINER=false check-generated-files
  depends_on:
  - clone
  image: grafana/loki-build-image:0.7.4
  name: check-generated-files
- commands:
  - make BUILD_IN_CONTAINER=false check-mod
  depends_on:
  - clone
  - test
  - lint
  image: grafana/loki-build-image:0.7.4
  name: check-mod
workspace:
  base: /src
  path: loki
---
depends_on:
- check
kind: pipeline
name: docker-amd64
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - apk add --no-cache bash git
  - git fetch origin --tags
  - echo $(./tools/image-tag)-amd64 > .tags
  image: alpine
  name: image-tag
- commands:
  - docker build -f cmd/loki/Dockerfile -t grafana/loki:$(./tools/image-tag)-amd64
  image: docker
  name: build-loki-image
  volumes:
  - name: docker_socket
  path: /var/run/docker.sock
  when:
    ref:
      exclude:
      - refs/heads/master
      - refs/tags/v*

volumes:
    - name: docker_socket
      host:
        path: /var/run/docker.sock
