grafana:
  enabled: true
  service:
    type: LoadBalancer
    port: 3000
  adminPassword: admin

prometheus:
  enabled: true
  pushgateway:
    enabled: false
  server:
    service:
      type: LoadBalancer
      servicePort: 9090

promtail:
  image:
    pullPolicy: Never
  pipelineStages:
  - docker: {}
  - regex:
      expression: (level|lvl|severity)=(?P<level>\w*)
      labels:
        level:
  - json:
      labels:
        level: 
          source: level || lvl || severity
      match: '{level=""}'

loki:
  image:
    pullPolicy: Never
  service:
    type: LoadBalancer