server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:
- job_name: system
  pipeline_stages:
  - regex:
      expr: "./*"
  - json:
      labels:
        test:
          source: stream
      output:
        source: log
  static_configs:
  - targets:
      - localhost
    labels:
      job: testlog
      __path__: /tmp/log/*.log