server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3200/api/prom/push

scrape_configs:
- job_name: system
  pipeline_stages:
    - json:
        labels:
          level:
          component:
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/myproject/*log
